# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "maven"
    # Look for a `pom.xml` in the `backend` directory
    directory: "/backend"
    schedule:
      interval: "weekly"
      time: "09:00"
    open-pull-requests-limit: 3
    target-branch: "dependabot"

  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `frontend` directory
    directory: "/frontend" # Location of package manifests
    schedule:
      interval: "weekly"
      time: "09:00"
    open-pull-requests-limit: 3
    target-branch: "dependabot"

  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `root` directory
    directory: "/"
    schedule:
      interval: "weekly"
      time: "09:00"
    open-pull-requests-limit: 3
    target-branch: "dependabot"
