server.port: 8098

spring:
  datasource.url: jdbc:sqlite:${DB_PATH}
  #  sql.init.mode: always
  jpa:
    #  defer-datasource-initialization: true
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate.ddl-auto: update
  security:
    user:
      name: ${USER_NAME}
      password: ${USER_SECRET}

logging:
  level:
    es.e1sordo.worknote.clients:
      NotionClient: DEBUG # Feign logging only responds to the DEBUG level
    root: INFO
