name: Docker Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17

      - name: Build with Maven
        run: mvn install

      - name: Build Docker image
        run: |
          docker build . --tag worknote:latest
          docker tag worknote:latest vlavik007/worknote:latest

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u vlavik007 --password-stdin

      - name: Push Docker image
        run: docker push vlavik007/worknote:latest

#      - name: Deploy to remote server
#        uses: appleboy/ssh-action@v0.3.0
#        with:
#          host: ${{ secrets.REMOTE_HOST }}
#          username: ${{ secrets.REMOTE_USERNAME }}
#          key: ${{ secrets.SSH_PRIVATE_KEY }}
#          port: ${{ secrets.REMOTE_PORT }}
#          script: |
#            docker-compose pull
#            docker-compose up -d
