name: Docker Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build_job:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17.0.0+35'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B install --no-transfer-progress

      - name: Archive .jar file
        uses: actions/upload-artifact@v3
        with:
          name: app-jar
          path: backend/target/backend-0.0.1-SNAPSHOT.jar
          if-no-files-found: error

    outputs:
      jar-file: ${{ runner.workspace }}/app.jar  # Declare the artifact output


  docker_deploy_job:
    runs-on: ubuntu-latest
    needs: build_job

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download .jar file
        uses: actions/download-artifact@v3
        with:
          name: app-jar
          path: backend/target

      - name: Build Docker image
        run: |
          docker build . --tag worknote:latest
          docker tag worknote:latest vlavik007/worknote:latest

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u vlavik007 --password-stdin

      - name: Push Docker image
        run: docker push vlavik007/worknote:latest

#      - name: Deploy to remote server
#        uses: appleboy/ssh-action@v0.3.0
#        with:
#          host: ${{ secrets.REMOTE_HOST }}
#          username: ${{ secrets.REMOTE_USERNAME }}
#          key: ${{ secrets.SSH_PRIVATE_KEY }}
#          port: ${{ secrets.REMOTE_PORT }}
#          script: |
#            docker-compose pull
#            docker-compose up -d
